### ISSUE TITLE
Not compatible with Mautic 3... :-(

### ISSUE THREAD

**Issue by stremshs** [mtcextendee/mautic-custom-deduplicate-bundle#2]
Hi guys, 
Thanks for all the work you did for the Mautic community.

Class "Mautic\CoreBundle\EventListener\CommonSubscriber" has been removed from Mautic 3, causing this plugin to be incompatible :
When trying to empty the cache after copying the folder into the "plugins" folder, here is the error displayed :

_In ClassExistenceResource.php line 181:
Class "Mautic\CoreBundle\EventListener\CommonSubscriber" not found while loading "MauticPlugin\MauticCustomDeduplicateBundle\EventListener\ButtonSubscriber"._ 

Any plan to do an update ? 
Thanks a lot !

**Comment by kuzmany** [comment]
No, any plan. 
If you are interest, let me know, I can do it for you

**Comment by phillipwilhelm** [comment]
I am interested in this as well.

**Comment by kuzmany** [comment]
It's already compatible with M3
