### ISSUE TITLE
Installing deduplicate on M4.1 

### ISSUE THREAD

**Issue by russkiimike** [mtcextendee/mautic-custom-deduplicate-bundle#3]
Hiya, trying to install this on M4.1

Getting an error when cleaning cache

```
In CheckDeduplicateContactsListener.php line 39:
                                                                 
  Undefined class constant 'CHECK_FOR_DUPLICATE_CONTACTS_EVENT'  
```

**Comment by kuzmany** [comment]
Plugin require this PR https://github.com/mautic/mautic/pull/9844. Did you patch your instance before installation?

**Comment by russkiimike** [comment]
What do you mean by that?

**Comment by russkiimike** [comment]
Any updates?

**Comment by kuzmany** [comment]
All of you need was written.
You need this change in your Mautic https://github.com/mautic/mautic/pull/9844 
And then you can use plugin.
But last time plugin was tested on M3, then cannot promise If it will work on M4
